# The Spark Foundation #GRIPJUNE2021

# Data Science and Business Analytics

# Author: Prasad Shinde

# Task 4: Prediction using Decision Tree Algorithm

In [1]:
# import the relevent package
import pandas as pd
import seaborn as sns
from sklearn import tree
from sklearn import preprocessing

import matplotlib.pyplot as plt
import numpy as np

In [11]:
# setting the working directory
import os as os
os.chdir("C:\\Users\\MyPC\\Desktop\\practice datasets")

In [12]:
os.getcwd()

'C:\\Users\\MyPC\\Desktop\\practice datasets'

In [13]:
os.listdir()

['.RData',
 '.Rhistory',
 'country_vaccinations.csv',
 'country_vaccinations_by_manufacturer.csv',
 'Fish.csv',
 'gender_submission.csv',
 'heart.csv',
 'HR_comma_sep.csv',
 'Iris.csv',
 'Log_ROC.png',
 'Melbourne_housing_FULL.csv',
 'My list-converted.xlsx',
 'o2Saturation.csv',
 'Real estate.csv',
 'SampleSuperstore.csv',
 'test.csv',
 'train.csv',
 'world-happiness-report-2021.csv',
 'world-happiness-report.csv']

In [14]:
df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [18]:
df.shape


(150, 6)

In [20]:
# labeling the Species column as 0,1 and 2
df["class"] = df["Species"].map({"Iris-setosa":0,'Iris-versicolor':1,"Iris-virginica":2}).astype(int)

In [21]:
X=np.array(df.iloc[:,0:4]) # inputs
Y=np.array(df["class"])    # output

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import tree
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.4,random_state=1)

In [23]:
# training the model
model=DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier()

In [24]:
# prediction on the x_test
prediction=model.predict(X_test)

In [25]:
# model accuracy
model.score(X_test,Y_test)

0.9833333333333333

In [26]:
# confusion matrix
cnf_matrix = confusion_matrix(Y_test, prediction)
print(cnf_matrix)

[[19  0  0]
 [ 0 20  1]
 [ 0  0 20]]
